import React from 'react';
import Link from '@docusaurus/Link';

`New Links for Removed Documentation

This file includes a complete list of all documentation that has been removed and its corresponding new links on the help center.`


const notFoundNewLinks  = {
  "/docs/artist_getting_started": <><Link to="https://help.ayon.app/en/help/articles/4678978-getting-started-with-ayon-pipeline">Getting Started with AYON Pipeline</Link></>,
  "/docs/artist_concepts": <><Link to="https://help.ayon.app/en/help/articles/3030530-ayon-glossary">AYON Glossary</Link></>,
  "/docs/artist_publish": <><Link to="https://help.ayon.app/en/help/articles/7070980-about-ayon-pipeline">About AYON Pipeline</Link></>,

  "/docs/artist_tools": <><Link to="https://help.ayon.app/en/help/collections/3002056-pipeline-tools">Pipeline Tools</Link></>,
  "/docs/artist_tools_creator": <><Link to="https://help.ayon.app/en/help/articles/1075843-creator-publisher">Creator / Publisher</Link></>,
  "/docs/artist_tools_loader": <><Link to="https://help.ayon.app/en/help/articles/4345209-loader">Loader</Link></>,
  "/docs/artist_tools_library_loader": <><Link to="https://help.ayon.app/en/help/articles/4345209-loader">Loader</Link></>,
  "/docs/artist_tools_publisher": <><Link to="https://help.ayon.app/en/help/articles/1075843-creator-publisher">Creator / Publisher</Link></>,
  "/docs/artist_tools_inventory": <><Link to="https://help.ayon.app/en/help/articles/9770233-scene-inventory">Scene Inventory</Link></>,
  "/docs/artist_tools_workfiles": <><Link to="https://help.ayon.app/en/help/articles/9624270-workfiles">Workfiles</Link></>,
  "/docs/artist_tools_look_assigner": <><Link to="https://help.ayon.app/en/help/articles/6062888-look-assigner">Look Assigner</Link></>,

  "/docs/addon_3dsmax_artist": <><Link to="https://help.ayon.app/en/help/articles/6074628-working-with-3ds-max-in-ayon">Working with 3ds Max in AYON</Link></>,
  "/docs/addon_3dequalizer_artist": <><Link to="https://help.ayon.app/en/help/articles/4884565-working-with-3dequalizer-in-ayon">Working with 3DEqualizer in AYON</Link></>,
  "/docs/addon_aftereffects_artist": <><Link to="https://help.ayon.app/en/help/articles/9429657-working-with-after-effects-in-ayon">Working with After Effects in AYON</Link></>,
  "/docs/addon_blender_artist": <><Link to="https://help.ayon.app/en/help/articles/2501380-working-with-blender-in-ayon">Working with Blender in AYON</Link></>,
  "/docs/addon_resolve_artist": <><Link to="https://help.ayon.app/en/help/articles/9472845-working-with-resolve-studio-in-ayon">Working with Resolve Studio in AYON</Link></>,
  "/docs/addon_ftrack_artist": <><Link to="https://help.ayon.app/en/help/articles/6899451-working-with-ftrack-in-ayon">Working with ftrack in AYON</Link></>,
  "/docs/addon_ftrack_manager": <><Link to="https://help.ayon.app/en/help/articles/0474911-ftrack-manager">ftrack Manager</Link></>,
  "/docs/addon_ftrack_actions": <><Link to="https://help.ayon.app/en/help/articles/0639073-ftrack-actions">ftrack Actions</Link></>,
  "/docs/addon_harmony_artist": <><Link to="https://help.ayon.app/en/help/articles/3580393-working-with-harmony-in-ayon">Working with Harmony in AYON</Link></>,
  "/docs/addon_hiero_artist": <><Link to="https://help.ayon.app/en/help/articles/0417137-working-with-hiero-in-ayon">Working with Hiero in AYON</Link></>,
  "/docs/addon_flame_artist": <><Link to="https://help.ayon.app/en/help/articles/5381712-working-with-autodesk-flame-in-ayon">Working with Autodesk Flame in AYON</Link></>,
  "/docs/addon_houdini_artist": <><Link to="https://help.ayon.app/en/help/articles/2777507-working-with-houdini-in-ayon">Working with Houdini in AYON</Link></>,
  "/docs/addon_houdini_artist_loader_hdas": <><Link to="https://help.ayon.app/en/help/articles/4210042-houdini-ayon-loader-hdas">Houdini AYON Loader HDAs</Link></>,
  "/docs/addon_jira_artist": <><Link to="https://help.ayon.app/en/help/articles/8465192-jira">Jira Addon</Link></>,
  "/docs/addon_kitsu_artist": <><Link to="https://help.ayon.app/en/help/articles/6394498-working-with-kitsu-in-ayon">Working with Kitsu in AYON</Link></>,
  "/docs/addon_maya_artist": <><Link to="https://help.ayon.app/en/help/articles/6811988-working-with-maya-in-ayon">Working with Maya in AYON</Link></>,
  "/docs/addon_maya_multiverse_artist": <><Link to="https://help.ayon.app/en/help/articles/7718098-working-with-multiverse-in-ayon">Working with Multiverse in AYON</Link></>,
  "/docs/addon_maya_yeti_artist": <><Link to="https://help.ayon.app/en/help/articles/4740816-working-with-yeti-in-ayon">Working with Yeti in AYON</Link></>,
  "/docs/addon_maya_xgen_artist": <><Link to="https://help.ayon.app/en/help/articles/7485931-working-with-xgen-in-ayon">Working with Xgen in AYON</Link></>,
  "/docs/addon_maya_ornatrix_artist": <><Link to="https://help.ayon.app/en/help/articles/7811185-working-with-ornatrix-in-ayon">Working with Ornatrix in AYON</Link></>,
  "/docs/addon_maya_arnold_artist": <><Link to="https://help.ayon.app/en/help/articles/2888902-working-with-arnold-in-ayon">Working with Arnold in AYON</Link></>,
  "/docs/addon_maya_vray_artist": <><Link to="https://help.ayon.app/en/help/articles/3842653-working-with-vray-in-ayon">Working with Vray in AYON</Link></>,
  "/docs/addon_maya_redshift_artist": <><Link to="https://help.ayon.app/en/help/articles/0021176-working-with-redshift-in-ayon">Working with Redshift in AYON</Link></>,
  "/docs/addon_motionbuilder_artist": <><Link to="https://help.ayon.app/en/help/articles/7411907-working-with-motionbuilder-in-ayon">Working with Motionbuilder in AYON</Link></>,
  "/docs/addon_nuke_artist": <><Link to="https://help.ayon.app/en/help/articles/4670584-working-with-nuke-in-ayon">Working with Nuke in AYON</Link></>,
  "/docs/addon_photoshop_artist": <><Link to="https://help.ayon.app/en/help/articles/7712931-working-with-photoshop-in-ayon">Working with Photoshop in AYON</Link></>,
  "/docs/addon_premiere_artist": <><Link to="https://help.ayon.app/en/help/articles/3607676-working-with-premiere-in-ayon">Working with Premiere in AYON</Link></>,
  "/docs/addon_substancepainter_artist": <><Link to="https://help.ayon.app/en/help/articles/2948998-working-with-substance-painter">Working with Substance Painter</Link></>,
  "/docs/addon_substancedesigner_artist": <><Link to="https://help.ayon.app/en/help/articles/8280887-working-with-substance-designer-in-ayon">Working with Substance Designer in AYON</Link></>,
  "/docs/addon_traypublisher_artist": <><Link to="https://help.ayon.app/en/help/articles/5385780-working-with-ayon-tray-publisher">Working with AYON Tray Publisher</Link></>,
  "/docs/addon_traypublisher_artist_advanced": <><Link to="https://help.ayon.app/en/help/articles/0866874-tray-publisher-for-tds">Tray Publisher for TDs</Link></>,
  "/docs/addon_tvpaint_artist": <><Link to="https://help.ayon.app/en/help/articles/8337707-working-with-tvpaint-in-ayon">Working with TVPaint in AYON</Link></>,
  "/docs/addon_unreal_artist": <><Link to="https://help.ayon.app/en/help/articles/2228078-working-with-unreal-in-ayon">Working with Unreal in AYON</Link></>,
  "/docs/addon_version_control_artist": <><Link to="https://help.ayon.app/en/help/articles/4584821-working-with-perforce-in-ayon">Working with Perforce in AYON
</Link></>,
  "/docs/addon_wrap_artist": <><Link to="https://help.ayon.app/en/help/articles/1462992-working-with-wrap-in-ayon">Working with Wrap in AYON</Link></>,
  "/docs/addon_openrv_artist": <><Link to="https://help.ayon.app/en/help/articles/5906891-working-with-openrv-in-ayon">Working with OpenRV in AYON</Link></>,
  // "/docs/addon_aquarium_artist": <><Link to="Page exists but marked as draft."></Link></>,
  // "/docs/addon_aquarium_manager": <><Link to="Page exists but marked as draft."></Link></>,
  "/docs/addon_cinema4d_artist": <><Link to="https://help.ayon.app/en/help/articles/7284251-working-with-ayon-in-cinema4d">Working with AYON in Cinema4D​</Link></>,
  "/docs/addon_zbrush_artist": <><Link to="https://help.ayon.app/en/help/articles/2471745-working-with-zbrush-in-ayon">Working with Zbrush in AYON</Link></>,
  "/docs/addon_mochapro_artist": <><Link to="https://help.ayon.app/en/help/articles/0309485-working-with-mocha-pro-in-ayon">Working with Mocha Pro in AYON</Link></>,
  "/docs/addon_silhouette_artist": <><Link to="https://help.ayon.app/en/help/articles/9127304-working-with-silhouette-in-ayon">Working with Silhouette in AYON</Link></>,
  "/docs/addon_speedtree_artist": <><Link to="https://help.ayon.app/en/help/articles/1430359-working-with-speedtree-in-ayon">Working with SpeedTree in AYON</Link></>,

  "/docs/artist_my_tasks_page": <><Link to="https://help.ayon.app/articles/2408349-tasks-home-page">Tasks (Home) Page</Link></>,
  "/docs/artist_details_panel": <><Link to="https://help.ayon.app/articles/0219162-the-details-panel">The Details Panel</Link></>,
  "/docs/artist_activity_feed": <><Link to="https://help.ayon.app/articles/8709483-the-activity-feed">The Activity Feed</Link></>,
  "/docs/artist_reviewables": <><Link to="https://help.ayon.app/articles/0359490-reviewables">Reviewables</Link></>,
  "/docs/artist_inbox": <><Link to="https://help.ayon.app/en/help/articles/7870202-inbox-and-notifications">Inbox and Notifications</Link></>,
  "/docs/artist_task_progress_page": <><Link to="https://help.ayon.app/en/help/articles/5526719-task-progress-page">Task Progress Page</Link></>,
  "/docs/addon_planner": <><Link to="https://help.ayon.app/en/help/articles/8736562-planner-addon">Planner Addon</Link></>,
  "/docs/system_introduction": <><Link to="https://help.ayon.app/en/help/articles/2243459-ayon-introduction">AYON Introduction</Link></>,
  "/docs/admin_releases": <><Link to="https://feedback.ayon.app/changelog">AYON Changelog</Link></>,
  "/docs/admin_import_openpype_project": <><Link to="https://help.ayon.app/en/help/articles/6657894-migrate-openpype-projects-to-ayon">Migrate OpenPype Projects to AYON</Link></>,

  
  "/docs/admin_server_deployment": <><Link to="https://help.ayon.app/en/help/articles/2293963-ayon-server-local-deployment">AYON Server Local Deployment</Link></>,
  "/docs/admin_server_configuration": <><Link to="https://help.ayon.app/en/help/articles/4287499-ayon-docker-configuration-options">AYON Docker Configuration Options</Link></>,
  "/docs/admin_server_installing_addons": <><Link to="https://help.ayon.app/en/help/articles/4089565-ayon-server-provisioning">AYON Server Provisioning</Link></>,
  "/docs/admin_server_provisioning": <><Link to="https://help.ayon.app/en/help/articles/4089565-ayon-server-provisioning">AYON Server Provisioning</Link></>,
  "/docs/admin_server_services": <><Link to="https://help.ayon.app/en/help/articles/7620452-ayon-service-host-ash">AYON Service Host (ASH)</Link></>,
  "/docs/admin_server_email": <><Link to="https://help.ayon.app/en/help/articles/4287499-ayon-docker-configuration-options">AYON Docker Configuration Options</Link></>,

  "/docs/admin_server_bundles_and_addons": <><Link to="https://help.ayon.app/en/help/articles/4644998-bundles-and-addons">Bundles & Addons</Link></>,
  "/docs/admin_server_market": <><Link to="https://help.ayon.app/en/help/articles/7317917-ayon-market">AYON Market</Link></>,
  "/docs/admin_server_updating_pipeline": <><Link to="https://help.ayon.app/en/help/articles/7772807-updating-pipeline-to-latest-release">Updating Pipeline to latest Release</Link></>,
  "/docs/admin_server_permissions": <><Link to="https://help.ayon.app/en/help/articles/2635883-user-permissions-and-project-access-groups">User Permissions and Project Access Groups</Link></>,
  "/docs/admin_server_power_features": <><Link to="https://help.ayon.app/en/help/articles/7017685-power-features">Power Features</Link></>,
  "/docs/admin_server_licenses": <><Link to="https://help.ayon.app/en/help/articles/6592804-ayon-licenses">AYON Licenses</Link></>,
  "/docs/admin_environment": <><Link to="/docs/dev_launcher#environment-variables">Launcher Environment Variables</Link></>,
  "/docs/admin_settings": <><Link to="https://help.ayon.app/en/help/articles/8317800-working-with-settings">Working with settings</Link></>,
  "/docs/admin_colorspace": <><Link to="https://help.ayon.app/en/help/articles/1279384-colorspace-settings">Colorspace Settings</Link></>,
  "/docs/admin_settings_project_anatomy": <><Link to="https://help.ayon.app/en/help/articles/3815114-project-anatomy">Project Anatomy</Link></>,
  "/docs/addon_core_settings": <><Link to="https://help.ayon.app/en/help/articles/3005275-core-addon-settings">Core Addon Settings</Link></>,
  "/docs/addon_applications_admin": <><Link to="https://help.ayon.app/en/help/articles/3945756-applications-and-tools">Applications and Tools</Link></>,
  "/docs/addon_3dsmax_admin": <><Link to="https://help.ayon.app/en/help/articles/0829992-configure-3dequalizer-addon">Configure 3DEqualizer Addon</Link></>,
  "/docs/addon_3dequalizer_admin": <><Link to="https://help.ayon.app/en/help/articles/3959010-3ds-max-addon-settings">3ds Max Addon Settings</Link></>,
  "/docs/addon_aftereffects_admin": <><Link to="https://help.ayon.app/en/help/articles/4515672-aftereffects-addon-settings">AfterEffects Addon Settings</Link></>,
  "/docs/addon_blender_admin": <><Link to="https://help.ayon.app/en/help/articles/6836825-configure-blender-addon">Configure Blender Addon</Link></>,
  "/docs/addon_resolve_admin": <><Link to="https://help.ayon.app/en/help/articles/3786946-configure-resolve-studio-to-work-with-ayon">Configure Resolve Studio to Work with AYON</Link></>,
  "/docs/addon_deadline_admin": <><Link to="https://help.ayon.app/en/help/articles/5372986-configure-deadline-addon">Configure Deadline Addon</Link></>,
  "/docs/addon_ftrack_admin": <><Link to="https://help.ayon.app/articles/1229195-configure-ftrack-addon">Configure ftrack Addon</Link></>,
  "/docs/addon_harmony_admin": <><Link to="https://help.ayon.app/en/help/articles/5752971-harmony-addon-settings">Harmony Addon Settings</Link></>,
  "/docs/addon_hiero_admin": <><Link to="https://help.ayon.app/en/help/articles/3397387-configure-hiero-addon">Configure Hiero Addon</Link></>,
  "/docs/addon_houdini_admin": <><Link to="https://help.ayon.app/en/help/articles/0982414-configure-houdini-addon">Configure Houdini Addon</Link></>,
  "/docs/addon_keycloak_admin": <><Link to="https://help.ayon.app/en/help/articles/3555427-keycloak">Keycloak</Link></>,
  "/docs/addon_maya_admin": <><Link to="https://help.ayon.app/en/help/collections/8127361-maya-addon-settings">Maya Addon Settings</Link></>,
  "/docs/addon_maya_ornatrix_admin": <><Link to="https://help.ayon.app/en/help/collections/8127361-maya-addon-settings">Maya Addon Settings</Link></>,
  "/docs/addon_motionbuilder_admin": <><Link to="https://help.ayon.app/en/help/articles/8914380-configure-motionbuilder-addon">Configure Motionbuilder Addon</Link></>,
  "/docs/addon_nuke_admin": <><Link to="https://help.ayon.app/en/help/articles/2833967-nuke-addon-settings">Nuke Addon Settings</Link></>,
  "/docs/addon_photoshop_admin": <><Link to="https://help.ayon.app/en/help/articles/0146725-photoshop-addon-settings">Photoshop Addon Settings</Link></>,
  "/docs/addon_premiere_admin": <><Link to="https://help.ayon.app/en/help/articles/1663762-premiere-addon-settings">Premiere Addon Settings</Link></>,
  "/docs/addon_site_sync_admin": <><Link to="https://help.ayon.app/en/help/articles/3882937-site-sync">Site Sync</Link></>,
  "/docs/addon_slack_admin": <><Link to="https://help.ayon.app/articles/8988101-slack">Slack</Link></>,
  "/docs/addon_sso_admin": <><Link to="https://help.ayon.app/en/help/articles/7917548-single-sign-on">Single Sign-On</Link></>,
  "/docs/addon_substancepainter_admin": <><Link to="https://help.ayon.app/en/help/articles/6244730-substance-painter-addon-settings">Substance Painter Addon Settings</Link></>,
  "/docs/addon_substancedesigner_admin_tutorials": <><Link to="https://help.ayon.app/en/help/articles/4514163-configure-substance-designer-addon">Configure Substance Designer Addon</Link></>,
  "/docs/addon_substancedesigner_admin_settings": <><Link to="https://help.ayon.app/en/help/articles/7771155-substance-designer-addon-settings">Substance Designer Addon Settings</Link></>,
  "/docs/addon_tvpaint_admin": <><Link to="https://help.ayon.app/en/help/articles/8770967-tvpaint-addon-settings">TVPaint Addon Settings</Link></>,
  "/docs/addon_unreal_admin": <><Link to="https://help.ayon.app/en/help/articles/8279245-unreal-addon-settings"></Link></>,
  "/docs/addon_kitsu_admin": <><Link to="https://help.ayon.app/articles/3271341-kitsu-addon-settings">Unreal Addon Settings</Link></>,
  "/docs/addon_jira_admin": <><Link to="https://help.ayon.app/articles/8465192-jira">Jira Addon</Link></>,
  "/docs/addon_clockify_admin": <><Link to="https://help.ayon.app/articles/0909886-clockify">Clockify</Link></>,
  "/docs/addon_traypublisher_admin": <><Link to="https://help.ayon.app/en/help/articles/3201789-tray-publisher-addon-settings">Tray Publisher Addon Settings</Link></>,
  "/docs/addon_wrap_admin": <><Link to="https://help.ayon.app/en/help/articles/0840796-wrap-addon-settings">Wrap Addon Settings</Link></>,
  "/docs/addon_syncsketch_admin": <><Link to="https://help.ayon.app/articles/0905719-syncsketch">SyncSketch Addon</Link></>,
  "/docs/addon_flow_admin": <><Link to="https://help.ayon.app/articles/3639938-configure-flow-shotgrid-addon">Configure Flow (ShotGrid) Addon</Link></>,
  "/docs/addon_flame_admin_intro": <><Link to="https://help.ayon.app/en/help/articles/3647766-setup-autodesk-flame-addon">Setup Autodesk Flame Addon</Link></>,
  "/docs/addon_flame_admin_get_started": <><Link to="https://help.ayon.app/en/help/articles/3647766-setup-autodesk-flame-addon">Setup Autodesk Flame Addon</Link></>,
  "/docs/addon_flame_admin_settings": <><Link to="https://help.ayon.app/en/help/articles/8354392-autodesk-flame-addon-settings">Autodesk Flame Addon Settings</Link></>,
  // "/docs/addon_aquarium_admin": <><Link to="exists as draft."></Link></>,
  "/docs/addon_usd_admin": <><Link to="https://help.ayon.app/en/help/articles/8466002-openusd-addon-settings">OpenUSD Addon Settings</Link></>,
  "/docs/addon_version_control_admin_intro": <><Link to="https://help.ayon.app/en/help/articles/2946473-version-control-introduction">Version Control Introduction</Link></>,
  "/docs/addon_version_control_admin_get_started": <><Link to="https://help.ayon.app/en/help/articles/1233046-about-perforce-and-ayon">About Perforce & AYON</Link></>,
  "/docs/addon_version_control_admin_settings": <><Link to="https://help.ayon.app/en/help/articles/7771120-perforce-addon-settings">Perforce Addon Settings</Link></>,
  "/docs/addon_cinema4d_admin": <><Link to="https://help.ayon.app/en/help/articles/4858866-configure-cinema4d-addon">Configure Cinema4D Addon</Link></>,
  "/docs/addon_zbrush_admin": <><Link to="https://help.ayon.app/en/help/articles/2471745-working-with-zbrush-in-ayon">Working with Zbrush in AYON</Link></>,
  // "/docs/admin_webserver_for_webpublisher": <><Link to="obsolete"></Link></>,
  "/docs/addon_mochapro_admin": <><Link to="https://help.ayon.app/en/help/articles/3864909-mocha-pro-addon-settings">Mocha Pro Addon Settings</Link></>,
  "/docs/addon_silhouette_admin": <><Link to="https://help.ayon.app/en/help/articles/5294823-silhouette-addon-settings">Silhouette Addon Settings</Link></>,
  "/docs/addon_speedtree_admin": <><Link to="https://help.ayon.app/en/help/articles/9963950-configure-speedtree-addon">Configure SpeedTree Addon</Link></>,
  "/docs/admin_launcher_distribute": <><Link to="https://help.ayon.app/articles/2308428-launcher-admin-notes">Launcher - Admin Notes</Link></>,
  "/docs/admin_launcher_run": <><Link to="https://help.ayon.app/articles/2308428-launcher-admin-notes">Launcher - Admin Notes</Link></>,
  
  "/docs/category/usd": <><Link to="https://help.ayon.app/en/help/collections/3779298-openusd">AYON OpenUSD</Link></>,
  "/docs/addon_usd_artist_contribution_workflow": <><Link to="https://help.ayon.app/en/help/collections/4882924-ayon-openusd-contribution-workflow">AYON OpenUSD Contribution Workflow</Link></>,
  "/docs/addon_usd_artist_faq": <><Link to="https://help.ayon.app/en/help/collections/3779298-openusd">AYON OpenUSD</Link></>,
  "/docs/addon_usd_artist_get_started": <><Link to="https://help.ayon.app/en/help/articles/4158006-ayon-openusd-contribution-workflow">AYON OpenUSD Contribution Workflow</Link></>,
  "/docs/addon_usd_artist_houdini_workflow": <><Link to="https://help.ayon.app/en/help/articles/6171777-ayon-houdini-openusd-workflow">AYON Houdini OpenUSD Workflow</Link></>,
  "/docs/addon_usd_artist_maya_workflow": <><Link to="https://help.ayon.app/en/help/articles/7468381-ayon-maya-openusd-workflow">AYON Maya OpenUSD Workflow</Link></>,
  "/docs/addon_usd_artist_usd_intro": <><Link to="https://help.ayon.app/en/help/articles/6167506-why-and-what-is-openusd">Why and What is OpenUSD?</Link></>,
};

export default notFoundNewLinks;